version: '3'

services:
  webserver:
    image: httpd:2.4-alpine
    volumes:
      - ./:/usr/local/apache2/htdocs:ro
    ports:
      - 80:80
  node:
    image: node:lts-alpine
    volumes:
       - ./:/node
    working_dir: /node

